version: '3'

services:
  jprime-dev:
    image: kilfu0701/py3-postgres
    container_name: jprime-dev
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data:rw
    environment:
      TZ: JST-9
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=ja_JP.UTF-8 --lc-ctype=ja_JP.UTF-8 --lc-messages=ja_JP.UTF-8'
      POSTGRES_DB: jprime_development
    sysctls:
      net.core.somaxconn: 8192
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: "no"
